### ISSUE TITLE
Fixture Improvement

### ISSUE THREAD

**Issue by ghost** [Motiva-AI/clj-sqs-extended#13]
Leftover from the previous improvement iteration:

```
(sqs-ext/send-message @test-ext-sqs-client @test-standard-queue-url)
```

would be a very well-readable version, but this requires the atoms to be placed within the test ns. The client atom then needs to be passed into fixtures/with-test-ext-sqs-client which isn't that troublesome. Its more difficult
with the queues, because these should get setup fresh anytime with-...-queue gets called.

```
(with-...-queue client queue-name
  ...)
```

was a previous attempt to pass the atoms over to the fixtures ns, but that isn't much more readable than the  original let version.

**Comment by Quantisan** [comment]
@daisybytes `with-queue-listener-test` might be what you need. see usage here: https://github.com/Motiva-AI/backend-common/blob/master/test/backend_common/test_utils_test.clj#L31 you can define a handle-queue on the fly.
