### ISSUE TITLE
Multiple queues on same bucket

### ISSUE THREAD

**Issue by ghost** [Motiva-AI/clj-sqs-extended#2]
A naive extention of the AWS working example for using the extended library did not show any problems when having multiple queues use the same S3 bucket. To have the queues use different buckets they would need to be created with a different client configuration that ties to the different buckets then.

![two_queues_one_bucket](https://user-images.githubusercontent.com/66042369/86425203-77d05800-bd1f-11ea-8c98-6262373b5746.png)

**Comment by Quantisan** [comment]
👍
