### ISSUE TITLE
check that when auto-delete=false, and visibility-timeout has passed, that the message would be sent again

### ISSUE THREAD

**Issue by Quantisan** [Motiva-AI/clj-sqs-extended#46]
at the moment, `core-test/done-fn-handle-present-when-auto-delete-false` check that the message is still there by deleting the message again. And if it's a successful delete, then that means the message was still on the queue if auto-delete=false.

But that's not exactly the same behaviour we require. This is a critical feature of SQS that we rely on. So it would be better to mimic the behaviour as much as possible in the test.

One obstacle for testing this is I'm not sure if localstack's sqs server supports resending. If not, then this could be an integration test with a live queue.

**Comment by ghost** [comment]
I will have to check again, but I think I remember that in the beginning when we had the visibility functionality there was already a test in place where this worked fine with localstack. I'll have another look.
